import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sansita } from "next/font/google";


const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

const sansita = Sansita({
  subsets: ["latin"],
  variable: "--font-sansita",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${sansita.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
